version: '3.9'
services:

  database:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: {{app_name}}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      start_period: 2s
      retries: 3
  
  backend:
    build: .
    environment:
       DB_HOST: database
       DB_USER: postgres
       DB_PASSWORD: postgres
       DB_NAME: {{app_name}}
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - database  
